name: radix_tree
description: Dart implementation of the Radix Tree data structure.
version: 1.1.1
repository: https://github.com/ykmnkmi/radix-tree.dart/tree/master/
issue_tracker: https://github.com/ykmnkmi/radix-tree.dart/issues
homepage: https://github.com/ykmnkmi/radix-tree.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: ^1.4.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.4
