name: radix_tree
description: Dart implementation of the Radix Tree data structure.
version: 1.0.1
repository: https://github.com/ykmnkmi/radix-tree.dart/tree/master/
issue_tracker: https://github.com/ykmnkmi/radix-tree.dart/issues
homepage: https://github.com/ykmnkmi/radix-tree.dart

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies: 
  meta: ^1.2.4 

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
